docker run -p 5000:5000 \
-e DBHOST=$DBHOST \
-e DBUSER=$DBUSER \
-e DBPASSWORD=$DBPASSWORD \
-e OAUTH_ID=$OAUTH_ID \
-e OAUTH_SECRET=$OAUTH_SECRET \
-e OAUTHLIB_RELAX_TOKEN_SCOPE=1 \
-e OAUTHLIB_INSECURE_TRANSPORT=1 \
orders-app
